/**
 * @fileoverview Challenge-response helpers for sync authentication.
 */

import { hmacSha256 } from '../crypto/index';
import { getSecureRandomHex } from '../util/secureRandom';
import { spake2Start, spake2Finish, spake2Confirm } from './spake2';

export { constantTimeEquals } from '../crypto/index';

/**
 * Computes the HMAC-SHA-256 response to an auth challenge.
 *
 * @param challenge - Challenge string from the master.
 * @param passwordHash - Hex password hash used as the HMAC key.
 * @returns Hex-encoded challenge response.
 */
export function computeChallengeResponse(challenge: string, passwordHash: string): string {
  return hmacSha256(passwordHash, challenge);
}

/** Satellite proof for a master challenge (SPAKE2 when the master sent a share). */
export interface SyncAuthProof {
  response: string;
  spakeShare?: string;
}

/**
 * Builds the `auth` payload. Protocol v3 masters send `spakeShare`; the
 * satellite finishes SPAKE2 so HMAC(passwordHash) never hits the wire.
 * HMAC remains for v2 / share-less challenges.
 */
export function buildSyncAuthProof(
  passwordHash: string,
  challenge: string,
  peerSpakeShare?: string
): SyncAuthProof {
  if (peerSpakeShare) {
    const mine = spake2Start(passwordHash, 'B');
    const shared = spake2Finish(passwordHash, mine, peerSpakeShare, 'B');
    return { response: spake2Confirm(shared, challenge), spakeShare: mine.shareHex };
  }
  return { response: computeChallengeResponse(challenge, passwordHash) };
}

/** Domain separator: a server proof must never be usable as a challenge response. */
const SERVER_PROOF_PREFIX = 'pkey-server-proof|';

/**
 * Domain separator for host-identity proofs keyed by a random pairing secret
 * (never the vault auth verifier). Distinct from {@link SERVER_PROOF_PREFIX}
 * so a leaked pairing MAC cannot be replayed as a legacy vault proof.
 */
const HOST_PROOF_PREFIX = 'pkey-host-proof|';

/** Wire tag on `challenge.proofKind` for pairing-key host proofs. */
export const HOST_PROOF_KIND = 'host-pairing' as const;

/** Random pairing secret length in bytes (hex encoding is twice as long). */
export const HOST_PROOF_SECRET_BYTES = 32;

/** Hex length of {@link HOST_PROOF_SECRET_BYTES}. */
export const HOST_PROOF_SECRET_HEX_LENGTH = HOST_PROOF_SECRET_BYTES * 2;

const HOST_PROOF_SECRET_HEX_RE = /^[0-9a-f]{64}$/i;

/**
 * True when `value` is a 32-byte hex pairing secret.
 *
 * @param value - Untrusted input (auth_ok inner, localStorage, SecureStore).
 */
export function isHostProofSecretHex(value: unknown): value is string {
  return typeof value === 'string' && HOST_PROOF_SECRET_HEX_RE.test(value);
}

/**
 * Lowercases a valid pairing secret; returns `undefined` when the shape is wrong.
 *
 * @param value - Untrusted input.
 */
export function normalizeHostProofSecret(value: unknown): string | undefined {
  if (!isHostProofSecretHex(value)) return undefined;
  return value.toLowerCase();
}

/**
 * Generates a fresh random host-pairing secret (CSPRNG).
 */
export function generateHostProofSecret(): string {
  return getSecureRandomHex(HOST_PROOF_SECRET_BYTES);
}

/**
 * @deprecated Vault-keyed HMAC. Must not be returned on unauthenticated
 * `challenge` replies — it is an offline password oracle. Use
 * {@link computeHostProof} with a random pairing secret instead.
 *
 * @param clientNonce - Random nonce generated by the client for this handshake.
 * @param passwordHash - Hex password hash used as the HMAC key.
 * @returns Hex-encoded proof.
 */
export function computeServerProof(clientNonce: string, passwordHash: string): string {
  return hmacSha256(passwordHash, `${SERVER_PROOF_PREFIX}${clientNonce}`);
}

/**
 * Master's proof of holding the *pairing* secret, over a nonce chosen by the
 * client. Lets a satellite verify which master it reached after an IP change
 * without exposing an HMAC under the vault auth verifier.
 *
 * @param clientNonce - Random nonce generated by the client for this handshake.
 * @param hostProofSecret - Random pairing secret (not `passwordHash`).
 * @returns Hex-encoded proof.
 */
export function computeHostProof(clientNonce: string, hostProofSecret: string): string {
  return hmacSha256(hostProofSecret, `${HOST_PROOF_PREFIX}${clientNonce}`);
}
