#!/usr/bin/env node
/**
 * Post-build: embed single-file PWA HTML and static icon/manifest assets
 * into src/web/generated/ for the on-device SyncWebServer.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const distDir = join(root, 'packages/web-client/dist');
const publicDir = join(root, 'packages/web-client/public');
const htmlPath = join(distDir, 'index.html');
const outDir = join(root, 'src/web/generated');

/** Allowlist of files served next to the PWA HTML shell. */
const ASSET_FILES = [
  { file: 'brand-logo.png', mime: 'image/png' },
  { file: 'favicon.ico', mime: 'image/x-icon' },
  { file: 'favicon-16.png', mime: 'image/png' },
  { file: 'favicon-32.png', mime: 'image/png' },
  { file: 'favicon-48.png', mime: 'image/png' },
  { file: 'apple-touch-icon.png', mime: 'image/png' },
  { file: 'pwa-192.png', mime: 'image/png' },
  { file: 'pwa-512.png', mime: 'image/png' },
  { file: 'pwa-512-maskable.png', mime: 'image/png' },
  { file: 'manifest.webmanifest', mime: 'application/manifest+json' },
];

let html;
try {
  html = readFileSync(htmlPath, 'utf8');
} catch {
  console.error(`Missing ${htmlPath}. Run npm run build:web first.`);
  process.exit(1);
}

/**
 * Reads an allowlisted asset from dist (Vite copy) or public (source).
 * @param {string} file
 * @returns {Buffer}
 */
function readAsset(file) {
  const distPath = join(distDir, file);
  const publicPath = join(publicDir, file);
  if (existsSync(distPath)) return readFileSync(distPath);
  if (existsSync(publicPath)) return readFileSync(publicPath);
  throw new Error(`Missing PWA asset ${file} (looked in dist/ and public/).`);
}

mkdirSync(outDir, { recursive: true });

const htmlOut = join(outDir, 'pwaHtml.ts');
writeFileSync(
  htmlOut,
  `/** Auto-generated by scripts/embed-pwa.mjs — do not edit */\nexport const PWA_HTML: string = ${JSON.stringify(html)};\n`,
  'utf8'
);

/** @type {Record<string, { mime: string; body: string }>} */
const assets = {};
for (const { file, mime } of ASSET_FILES) {
  const buf = readAsset(file);
  assets[`/${file}`] = { mime, body: buf.toString('base64') };
}

const assetsOut = join(outDir, 'pwaAssets.ts');
writeFileSync(
  assetsOut,
  `/** Auto-generated by scripts/embed-pwa.mjs — do not edit */\nexport const PWA_ASSETS: Record<string, { mime: string; body: string }> = ${JSON.stringify(assets, null, 2)};\n`,
  'utf8'
);

const assetBytes = Object.values(assets).reduce(
  (sum, a) => sum + Buffer.from(a.body, 'base64').length,
  0
);
console.log(`Embedded PWA HTML (${html.length} bytes) → ${htmlOut}`);
console.log(`Embedded PWA assets (${Object.keys(assets).length} files, ${assetBytes} bytes) → ${assetsOut}`);
