/**
 * @fileoverview Shared styles for the device-migration flow and QR scanner.
 */
import { Platform, StyleSheet } from 'react-native';

export const migrationFlowStyles = StyleSheet.create({
  root: { flex: 1, paddingTop: Platform.OS === 'android' ? 36 : 0 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  backBtn: { width: 40, padding: 4 },
  headerTitle: { flex: 1, textAlign: 'center', fontSize: 17, fontWeight: '700' },
  body: { padding: 16, paddingBottom: 48 },
  warnBox: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    backgroundColor: 'rgba(239,68,68,0.06)',
  },
  stepper: { borderRadius: 12, borderWidth: 1, padding: 14, marginBottom: 16 },
  stepRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepLabel: { fontSize: 13 },
  progressBarWrap: { marginTop: 8 },
  progressBarBg: { height: 6, borderRadius: 3, overflow: 'hidden' },
  progressBarFill: { height: '100%', borderRadius: 3 },
  hint: { fontSize: 12, lineHeight: 17 },
  overview: { fontSize: 13, lineHeight: 19, marginBottom: 4, marginTop: 4 },
  fieldHelp: { fontSize: 11, lineHeight: 15, marginTop: 4, marginBottom: 2, opacity: 0.9 },
  qrSection: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    padding: 16,
    marginTop: 12,
  },
  qrCodePad: {
    marginTop: 4,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 8,
  },
  qrSkeleton: {
    width: 184,
    height: 184,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  qrSkeletonHint: {
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
    marginTop: 12,
    paddingHorizontal: 8,
  },
  detailsSkeleton: {
    minHeight: 88,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  sectionTitle: { fontSize: 14, fontWeight: '700', marginBottom: 12, alignSelf: 'flex-start' },
  subSectionTitle: { fontSize: 13, fontWeight: '600', marginTop: 12, marginBottom: 6 },
  methodDesc: { fontSize: 12, lineHeight: 18, marginBottom: 10 },
  methodHint: { fontSize: 11, lineHeight: 16, marginTop: 8 },
  modeTabs: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  modeTab: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  manualInfoBox: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 16,
    marginTop: 12,
  },
  manualInfoHeader: { flexDirection: 'row', alignItems: 'center' },
  manualInfoRow: { marginTop: 12 },
  manualInfoLabel: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  manualInfoValue: { fontSize: 15, marginTop: 4, fontWeight: '600' },
  pairingBlock: {
    marginTop: 8,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  pairingCode: {
    fontFamily: 'monospace',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginTop: 6,
  },
  fingerprintBox: { borderRadius: 12, borderWidth: 1, padding: 14 },
  fingerprintValue: {
    fontSize: 22,
    fontWeight: '700',
    fontFamily: 'monospace',
    letterSpacing: 2,
    marginTop: 6,
  },
  deviceList: { borderRadius: 12, borderWidth: 1, padding: 14, marginTop: 12 },
  deviceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  primaryBtn: {
    borderRadius: 10,
    padding: 16,
    alignItems: 'center',
    marginTop: 20,
  },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  qrPlaceholder: { alignItems: 'center', padding: 24, minHeight: 120, justifyContent: 'center' },
  qrPlaceholderText: { color: '#888', textAlign: 'center', marginTop: 8, fontSize: 12 },
  permBtn: { padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#666' },
  permBtnText: { color: '#aaa' },
  permBtnFilled: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  permBtnFilledText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  modernScanBox: { marginTop: 4 },
  modernScanBtn: { flexDirection: 'row', justifyContent: 'center', marginTop: 4 },
  cameraWrap: {
    height: 180,
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 8,
    backgroundColor: '#000',
  },
  cameraFill: { width: '100%', height: '100%' },
  scanActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  scanActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
  },
  scanActionText: { fontSize: 12, fontWeight: '600' },
  pairOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    padding: 20,
  },
  finalizeOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    padding: 22,
  },
  finalizeCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 20,
  },
  finalizeBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 8,
  },
  waitBox: {
    marginTop: 16,
    borderRadius: 12,
    borderWidth: 1,
    padding: 18,
    alignItems: 'center',
  },
  secBtn: {
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  secBtnText: { fontSize: 14, fontWeight: '600' },
  pairCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
  },
  fieldInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: 'monospace',
    fontSize: 15,
  },
});
